export const GET_CART_BY_ID_START = 'GET_CART_BY_ID_START';
export const GET_CART_BY_ID_SUCCESS = 'GET_CART_BY_ID_SUCCESS';
export const GET_CART_BY_ID_FAIL = 'GET_CART_BY_ID_FAIL';

export const DELETE_CART_BY_ID_START = 'DELETE_CART_BY_ID_START';
export const DELETE_CART_BY_ID_SUCCESS = 'DELETE_CART_BY_ID_SUCCESS';
export const DELETE_CART_BY_ID_FAIL = 'DELETE_CART_BY_ID_FAIL';

export const EDIT_CART_ITEM_START = 'EDIT_CART_ITEM_START';
export const EDIT_CART_ITEM_SUCCESS = 'EDIT_CART_ITEM_SUCCESS';
export const EDIT_CART_ITEM_FAIL = 'EDIT_CART_ITEM_FAIL';

export const EDIT_CART_ITEM_COUNT = 'EDIT_CART_ITEM_COUNT';

export const CLEAR_CART_STATE = 'CLEAR_CART_STATE';
