export const GET_PRODUCT_TYPES_START = 'GET_PRODUCT_TYPES_START';
export const GET_PRODUCT_TYPES_SUCCESS = 'GET_PRODUCT_TYPES_SUCCESS';
export const GET_PRODUCT_TYPES_FAIL = 'GET_PRODUCT_TYPES_FAIL';

export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_MORE_PRODUCTS_START = 'GET_MORE_PRODUCTS_START';
export const GET_MORE_PRODUCTS_SUCCESS = 'GET_MORE_PRODUCTS_SUCCESS';
export const GET_MORE_PRODUCTS_FAIL = 'GET_MORE_PRODUCTS_FAIL';